apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dgr11vvf2-go
  janus-idp.io/tekton: dgr11vvf2-go
  backstage.io/kubernetes-id: dgr11vvf2-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dgr11vvf2-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
